### ISSUE TITLE
10.13.5感觉字体很模糊

### ISSUE THREAD

**Issue by Easyzhan** [Sunnyyoung/SYFlatButton#12]
字体模糊

**Comment by iBourne** [comment]
@Easyzhan 
跟系统没关系，分辨率的问题，设置下 TextLayer 的缩放：
_titleLayer.contentsScale = NSScreen.mainScreen.backingScaleFactor;

**Comment by Easyzhan** [comment]
老哥，稳👌，在源码里的 titleLayer 设置上就得了
