### ISSUE TITLE
Setting titleNormalColor in Swift takes 10% CPU

### ISSUE THREAD

**Issue by ericdke** [Sunnyyoung/SYFlatButton#4]
Hello! Setting titleNormalColor on a SYFlatButton in Swift takes 10% CPU and then continues to hog resources forever. 

It _looks like_ an infinite loop. Xcode Instruments shows a lot of activity around Core Animation. 

If we set the titleNormalColor on many buttons, the resource consumption adds up. 

The title colors are set in IB then changed by code while the app is running. The buttons work great until titleNormalColor is set to a new color, then the CPU jumps +10% *per changed button* and stays there.

Don't hesitate to ask me for details or code example if needed! :)

**Comment by Sunnyyoung** [comment]
@ericdke Fixed it! See e60860f14ec46dde9beaf16d768be60abd1d3dbb.

**Comment by ericdke** [comment]
@Sunnyyoung Thanks! :)
