### ISSUE TITLE
macOS 10.11无法正常使用

### ISSUE THREAD

**Issue by lilthree** [Sunnyyoung/SYFlatButton#6]
看到支持的版本是10.9以上，但是10.11无法正常使用

**Comment by Sunnyyoung** [comment]
@lilthree 能否给更多的信息呢

**Comment by lilthree** [comment]
@Sunnyyoung CALayerDelegate 这个提示找不到，imageHugsTitle这个参数，以及NSImageLeading、NSImageTrailing没有

**Comment by Sunnyyoung** [comment]
@lilthree 查了下，提及的 API 是 10.12 以上才适用的😓，这一部分没有测试到，看来目前暂时只能在 10.12 以上使用了。
当然通过适配是可以做到的，但是时间不是很充裕。
